mappingfrom = ["simpósio brasileiro de engenharia de software",
               "simpósio brasileiro de engenharia de sistemas computacionais", 
               "simpósio brasileiro de sistemas multimídia e web",
               "global iot summit",
               "workshop de computação urbana", 
               "the 24th brazilian symposium",
               "workshop-school on agents, environments, and applications", 
               "the 12th acm/ieee international symposium", 
               "xp ?18 companion", 
               "18\u00ba sbmo ? simp\u00f3sio brasileiro de micro-ondas e optoeletr\u00f4nica",
               "the 17th brazilian symposium", 
               'the 33rd annual acm symposium', 
               "momag", 
               "the xxxii brazilian symposium", 
               "brazilian symposium on human factors in computing systems", 
               "workshop de computa\u00c7\u00c3o urbana", 
               "the xvi brazilian symposium", 
               "the 31st brazilian symposium",
               "the xxiii brazilian symposium", 
               "the 18th brazilian symposium", 
               "the 34th acm/sigapp symposium", 
               "the xv brazilian symposium", 
               "the 25th brazillian symposium", 
               "icwmc", 
               "the euro american conference",
               "conferência latino-americana de tecnologias de aprendizagem", 
               "16th ergodesign & usihc e cinahpa 2017", 
               "ies ieee industrial electronics society (ies)", 
               "iberchip", 
               "the 23rd brazillian symposium", 
               "the 32nd symposium",
               "the 14th acm international symposium", 
               "acm latin america research catalyst workshop", 
               "wosar: the 11th international workshop on software aging and rejuvenation",
               "companion the 2019 world wide web conference", 
               "european symposium on artificial neural networks", 
               "brazilian symposium on computer games and digital entertainment", 
               "analyzing cleaning robots using probabilistic model checking", 
               "the acm symposium",
               "the 8th acm sigsoft international workshop", 
               "the symposium", 
               "international symposium on computer and information sciences in conjunction with the ifip world congress 2018", 
               "s4si", 
               "the xxxiii brazilian symposium", 
               "(bnaic", 
               "the xiii brazilian symposium", 
               "the xviii brazilian symposium",
               "conference of the centre for advanced studies on collaborative research", 
               "brazilian symposium on information systems", 
               "the xiv brazilian symposium", 
               "brazilian symposium on computer music", 
               "the 5th workshop",
               "the afternoon workshop", 
               "the acm sigchi symposium",
               "brazilian symposium on software quality", 
               "the 21st brazilian symposium",
               "the xxii brazilian symposium",
               "adjunct publication of the 26th conference",
               "frontiers in eduaction",
               "conferência ibérica de sistemas e tecnologias de informação",
               "simpósio brasileiro de componentes, arquiteturas e reuso",
               "brazilian symposium on human factors incomputing systems",
               "the 18th annual international conference",
               "empirical software engineering and measurement",
               "the 2nd workshop",
               "the 11th brazilian symposium",
               "the 26th conference",
               "the 16th acm sigplan international conference",
               "achi ",
               "the 16th workshop",
               "the 27th acm sigsoft international symposium",
               "the 19th annual international conference",
               "congresso ibero-americano de engenharia de software",
               "the 12th european conference",
               "the web conference 2019 1st workshop on fairness, accountability, transparency, ethics, and society on the web nfates 2019",
               "(jsos)",
               "congresso ibero-americano em engenharia de software",
               "(whases)",
               "(emicro/sim)",
               "simp\u00f3sio sul de microeletr\u00f4nica",
               "latin american computing conference (clei) - latin american symposium on computing and society (slis)",
               "frontiers in education",
               "simp\u00f3sio brasileiro de autom\u00e1tica",
               "xxxvii congresso da sociedade brasileira de computa\u00e7\u00e3",
               "brazilian symposium on computers in education (simp\u00d3sio brasileiro de inform\u00c1tica na educa\u00c7\u00c3o - sbie)",
               "Iberian Latin American Congress on Computational Methods in Engineering",
               "IEEE LARS?2017 ? 14rd Latin American Robotics Symposium",
               "Latin American Computing Conference",
               "lascas",
               "Latin American Robotics Symposium",
               "Latin American Robotics Symposium / Brazilian Symposium of Robotics",
               "Simposio Sul de Microeletr\u00f4nica",
               "Workshop on Multi-agent-based Simulation",
               "the 13th European Conference",
               "Proceedings of the 2019 Conference of the International Fuzzy Systems Association and the European Society for Fuzzy Logic and Technology (EUSFLAT 2019)",
               "(Brazilian Symposium on Computers in Education)",
               "ACM SAC",
               "IFSA-SCIS",
               "Latin American Robotics Symposium and Brazilian Symposium of Robotics",
               "World Congress oflnternational Fuzzy Systems Association and 9th International Conference on Soft Computing and Intelligent Systems",
               "ERGODESIGN & USIHC e CINAHPA",
               "Engineering Multi-Agent Systems"
               ]

mappingto = ["Brazilian Symposium on Software Engineering",
             "Brazilian Symposium on Computing System Engineering",
             "(WEBMEDIA) Brazilian Symposium on Multimedia and the Web", 
             "GLOBAL INTERNET OF THINGS SUMMIT",
             "Workshop of Urban Computing", 
             "(WEBMEDIA) Brazilian Symposium on Multimedia and the Web",
             "(WESAAC) Workshop-Escola de Sistemas Agentes, seus Ambientes e apliCações",
             "ACM/IEEE International Symposium on Empirical Software Engineering and Measurement",
             "International Conference on Agile Software Development",
             "18th SBMO/IEEE MTT-S International Microwave and Optoelectronics Conference",
             "Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "ACM Symposium on Applied Computing",
             "SBMO/IEEE MTT-S International Microwave and Optoelectronics Conference",
             "Brazilian Symposium on Software Engineering",
             "Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "Workshop of Urban Computing",
             "Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "Brazilian Symposium on Software Engineering", 
             "Brazilian Symposium on Programming Languages",
             "Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "(SAC) ACM Symposium on Applied Computing",
             "Simpósio Brasileiro de Sistemas de Informação",
             "(WEBMEDIA) Brazilian Symposium on Multimedia and the Web",
             "ICWMC-IARIA",
             "(EATIS) Euro American Conference on Telematics and Information Systems", '(LACLO) Latin American Conference on Learning Objects and Technologies', "(USIHC) Congresso Internacional de Ergonomia e Usabilidade de Interfaces Humano Computador",
             "(IECON) Annual Conference of the IEEE Industrial Electronics Society",
             "Workshop Iberchip",
             "(WEBMEDIA) Brazilian Symposium on Multimedia and the Web","(SBCCI) Symposium on Integrated Circuits and Systems Design",
             "(Q2SWinet) ACM Symposium on QoS and Security for Wireless and Mobile Networks",
             "(CLIHC) Latin American Conference on Human Computer Interaction",
             "(ISSREW) IEEE International Symposium on Software Reliability Engineering Workshops",
             "(WWW) International World Wide Web Conferences",
             "(ESANN) European Symposium on Artificial Neural Networks",
             "Simpósio Brasileiro de Jogos e Entretenimento Digital",
             "IEEE International Conference on Information Reuse and Integration",
             "ACM Symposium on Document Engineering",
             "(A-TEST) EST - International Workshop on Automating Test Case Design, Selection and Evaluation",
             "(SAC) ACM Symposium on Applied Computing",
             "(ISCIS) International Symposium on Computer and Information Sciences",
             "NETSOFT",
             "(SBES) Brazilian Symposium on Software Engineering",
             "(BNAIC) - BNAIC",
             "(SBCARS) Brazilian Symposium on Components, Architectures and Reuse Software",
             "(SBQS) Simpósio Brasileiro de Qualidade de Software",
             "Annual International Conference on Computer Science and Software Engineering",
             "Simpósio Brasileiro de Sistemas de Informação",
             "SBSI",
             "(SBCM) Simpósio Brasileiro de Computação Musical",
             "(M4IOT) Workshop on Middleware for Context-Aware Applications in the IoT",
             "Proceedings of the Afternoon Workshop on Self-Driving Networks",
             "(EICS) ACM SIGCHI Symposium on Engineering Interactive Computing Systems",
             "(VEM) Workshop on Software Visualization, Evolution and Maintenance",
             "(SBQS) Simpósio Brasileiro de Qualidade de Software",
             "(SBLP) Brazilian Symposium on Programming Languages",
             "(SBLP) Brazilian Symposium on Programming Languages",
             "(UMAP) International Conference on User Modeling, Adaptation and Personalization",
             "(FIE)IEEE Frontiers in Education Conference",
             "Iberian Conference on Information Systems and Technologies",
             "(SBCARS) Brazilian Symposium on Components, Architectures and Reuse Software",
             "(IHC) Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "(DGO) Annual International Conference on Digital Government Research",
             "(ESEM) ACM/IEEE International Symposium on Empirical Software Engineering and Measurement",
             "(WASHES) Workshop on Social, Human, and Economic Aspects of Software",
             "(SBCARS) Brazilian Symposium on Components, Architectures and Reuse Software",
             "(ICPC) International Conference on Program Comprehension","GPCE	ACM International Conference on Generative Programming: Concepts and Experiences",
             "ACHI-IARIA",
             "(ARM) Workshop on Adaptive and Reflective Middleware",
             "(ISSTA) International Symposium on Software Testing and Analysis",
             "(DGO) Annual International Conference on Digital Government Research",
             "(CIbSE) Conferencia Iberoamericana de Software Engineering",
             "(ECSA) European Conference on Software Architecture",
             "(WWW) International World Wide Web Conferences",
             "(SESoS)",
             "Conferencia Iberoamericana de Software Engineering",
             "(WASHES)",
             "(SSM)",
             "South Symposium on Microelectronics",
             "(CLEI) Conferencia Latinoamericana de Informática",
             "(FIE)IEEE Frontiers in Education Conference",
             "Simpósio Brasileiro de Automação Inteligente",
            "(SBIE) Simpósio Brasileiro de Informática na Educação",
            "(CILAMCE) Iberian Latin American Congress on Computational Methods",
            "(LARS) IEEE Latin American Robotics Symposium",
            "(CLEI) Conferencia Latinoamericana de Informática",
            "(LASCAS)",
            "(LARS) IEEE Latin American Robotics Symposium",
            "(LARS) IEEE Latin American Robotics Symposium",
            "South Symposium on Microelectronics",
            "(MABS) International Workshop on Multi-Agent Based Simulation",
            "(ECSA) European Conference on Software Architecture",
            "(EUSFLAT) Conference of the European Society for Fuzzy Logic and Technology",
            "(SBIE)",
            "SAC",
            "(IFSA)",
            "Simpósio Brasileiro de Robótica",
            "(IFSA) World Congress of International Fuzzy Systems Association",
            "(USIHC) Congresso Internacional de Ergonomia e Usabilidade de Interfaces Humano Computador",
            "(EMAS) International Workshop on Engineering Multiagent Systems"
            ]

