mappingto = ["Brazilian Symposium on Software Engineering",
             "Brazilian Symposium on Computing System Engineering",
             "(WEBMEDIA) Brazilian Symposium on Multimedia and the Web", 
             "GLOBAL INTERNET OF THINGS SUMMIT",
             "Workshop of Urban Computing", 
             "(WEBMEDIA) Brazilian Symposium on Multimedia and the Web",
             "(WESAAC) Workshop-Escola de Sistemas Agentes, seus Ambientes e apliCações",
             "ACM/IEEE International Symposium on Empirical Software Engineering and Measurement",
             "International Conference on Agile Software Development",
             "18th SBMO/IEEE MTT-S International Microwave and Optoelectronics Conference",
             "Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "ACM Symposium on Applied Computing",
             "SBMO/IEEE MTT-S International Microwave and Optoelectronics Conference",
             "Brazilian Symposium on Software Engineering",
             "Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "Workshop of Urban Computing",
             "Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "Brazilian Symposium on Software Engineering", 
             "Brazilian Symposium on Programming Languages",
             "Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "(SAC) ACM Symposium on Applied Computing",
             "Simpósio Brasileiro de Sistemas de Informação",
             "(WEBMEDIA) Brazilian Symposium on Multimedia and the Web",
             "ICWMC-IARIA",
             "(EATIS) Euro American Conference on Telematics and Information Systems", 
             '(LACLO) Latin American Conference on Learning Objects and Technologies', 
             "(USIHC) Congresso Internacional de Ergonomia e Usabilidade de Interfaces Humano Computador",
             "(IECON) Annual Conference of the IEEE Industrial Electronics Society",
             "Workshop Iberchip",
             "(WEBMEDIA) Brazilian Symposium on Multimedia and the Web","(SBCCI) Symposium on Integrated Circuits and Systems Design",
             "(SBCCI) Symposium on Integrated Circuits and Systems Design"
             "(Q2SWinet) ACM Symposium on QoS and Security for Wireless and Mobile Networks",
             "(CLIHC) Latin American Conference on Human Computer Interaction",
             "(ISSREW) IEEE International Symposium on Software Reliability Engineering Workshops",
             "(WWW) International World Wide Web Conferences",
             "(ESANN) European Symposium on Artificial Neural Networks",
             "Simpósio Brasileiro de Jogos e Entretenimento Digital",
             "IEEE International Conference on Information Reuse and Integration",
             "ACM Symposium on Document Engineering",
             "(A-TEST) EST - International Workshop on Automating Test Case Design, Selection and Evaluation",
             "(SAC) ACM Symposium on Applied Computing",
             "(ISCIS) International Symposium on Computer and Information Sciences",
             "NETSOFT",
             "(SBES) Brazilian Symposium on Software Engineering",
             "(BNAIC) - BNAIC",
             "(SBCARS) Brazilian Symposium on Components, Architectures and Reuse Software",
             "(SBQS) Simpósio Brasileiro de Qualidade de Software",
             "Annual International Conference on Computer Science and Software Engineering",
             "Simpósio Brasileiro de Sistemas de Informação",
             "SBSI",
             "(SBCM) Simpósio Brasileiro de Computação Musical",
             "(M4IOT) Workshop on Middleware for Context-Aware Applications in the IoT",
             "Proceedings of the Afternoon Workshop on Self-Driving Networks",
             "(EICS) ACM SIGCHI Symposium on Engineering Interactive Computing Systems",
             "(VEM) Workshop on Software Visualization, Evolution and Maintenance",
             "(SBQS) Simpósio Brasileiro de Qualidade de Software",
             "(SBLP) Brazilian Symposium on Programming Languages",
             "(UMAP) International Conference on User Modeling, Adaptation and Personalization",
             "(FIE)IEEE Frontiers in Education Conference",
             "Iberian Conference on Information Systems and Technologies",
             "(SBCARS) Brazilian Symposium on Components, Architectures and Reuse Software",
             "(IHC) Simpósio Brasileiro sobre Fatores Humanos em Sistemas Computacionais",
             "(DGO) Annual International Conference on Digital Government Research",
             "(ESEM) ACM/IEEE International Symposium on Empirical Software Engineering and Measurement",
             "(WASHES) Workshop on Social, Human, and Economic Aspects of Software",
             "(SBCARS) Brazilian Symposium on Components, Architectures and Reuse Software",
             "(ICPC) International Conference on Program Comprehension",
             "(GPCE) ACM International Conference on Generative Programming: Concepts and Experiences",
             "ACHI-IARIA",
             "(ARM) Workshop on Adaptive and Reflective Middleware",
             "(ISSTA) International Symposium on Software Testing and Analysis",
             "(DGO) Annual International Conference on Digital Government Research",
             "(CIbSE) Conferencia Iberoamericana de Software Engineering",
             "(ECSA) European Conference on Software Architecture",
             "(WWW) International World Wide Web Conferences",
             "(SESoS)",
             "Conferencia Iberoamericana de Software Engineering",
             "(WASHES)",
             "(SSM)",
             "South Symposium on Microelectronics",
             "(CLEI) Conferencia Latinoamericana de Informática", 
             "(FIE)IEEE Frontiers in Education Conference",
             "Simpósio Brasileiro de Automação Inteligente",
             "(SBCUP) Simpósio Brasileiro de Computação Ubíqua e Pervasiva",
             "(SBIE) Simpósio Brasileiro de Informática na Educação",
             "(CILAMCE) Iberian Latin American Congress on Computational Methods",
             "(LARS) IEEE Latin American Robotics Symposium",
             "(CLEI) Conferencia Latinoamericana de Informática",
            "(LASCAS)",
            "(LARS) IEEE Latin American Robotics Symposium",
            "(LARS) IEEE Latin American Robotics Symposium",
            "South Symposium on Microelectronics",
            "(MABS) International Workshop on Multi-Agent Based Simulation",
            "(ECSA) European Conference on Software Architecture",
            "(EUSFLAT) Conference of the European Society for Fuzzy Logic and Technology",
            "(SBIE)",
            "SAC",
            "(IFSA)",
            "Simpósio Brasileiro de Robótica",
            "(IFSA) World Congress of International Fuzzy Systems Association",
            "(USIHC) Congresso Internacional de Ergonomia e Usabilidade de Interfaces Humano Computador",
            "(EMAS) International Workshop on Engineering Multiagent Systems"]

